name: Build and Deploy OpenAPI Docs

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.jsをセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: npmキャッシュの復元
        uses: actions/cache@v4
        id: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache
      
      - name: 依存関係をインストール（キャッシュがない場合のみ）
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install

      - name: TypeSpec CLIをインストール
        run: npm install -g @typespec/compiler

      - name: OpenAPIスキーマを生成
        run: |
          mkdir -p output
          tsp compile . --emit @typespec/openapi3 --output-dir tsp-output

      - name: GitHub Pages用に公開ファイルを準備
        run: |
          mkdir -p public
          cp tsp-output/schema/openapi.yaml public/
          echo "<meta http-equiv=\"refresh\" content=\"0; url=openapi.yaml\">" > public/index.html

      - name: GitHub Pagesへデプロイ
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: GitHub Pagesへデプロイ
        id: deployment
        uses: actions/deploy-pages@v4
